name: Subdomain Scan
on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Target Domain'
        required: true
jobs:
  recon:
    runs-on: ubuntu-latest
    steps:
      - name: Install Subfinder & Nuclei
        run: |
          go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
          go install -v github.com/projectdiscovery/nuclei/v3/cmd/nuclei@latest
          sudo mv ~/go/bin/* /usr/local/bin/
      - name: Run Scan
        run: |
          subfinder -d ${{ github.event.inputs.target }} -o subs.txt
          nuclei -l subs.txt -severity critical,high -o results.txt
      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: recon-results
          path: results.txt
          
